[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docker>=7.1,<7.2",
    "fastapi>=0.115,<0.116",
    "httpx>=0.28,<0.29",
    "mcp>=1.26.0",
    "pydantic-settings>=2.7,<2.8",
    "python-multipart==0.0.18",
    "redis[hiredis]>=5.2,<5.3",
    "sse-starlette>=3.0.3",
    "uvicorn[standard]>=0.34,<0.35",
    "websockets==14.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3,<8.4",
    "pytest-asyncio>=0.25,<0.26",
]
