apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-executor.fullname" . }}-config
  labels:
    {{- include "code-executor.labels" . | nindent 4 }}
data:
  # Map all string/JSON values dynamically from Values.config
  {{- range $key, $val := .Values.config }}
  {{ printf "CODE_EXEC_%s" ($key | upper) }}: {{ $val | quote }}
  {{- end }}
