apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-executor.fullname" . }}-secrets
  labels:
    {{- include "code-executor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretConfig }}
  {{ printf "CODE_EXEC_%s" ($key | upper) }}: {{ $val | b64enc | quote }}
  {{- end }}
