{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-executor.fullname" . }}-redis
  labels:
    {{- include "code-executor.labels" . | nindent 4 }}
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: code-executor
    component: redis
{{- end }}
